import sys
import os
from datetime import datetime
from typing import get_type_hints, Literal, Union, get_origin, get_args, List, Dict
import enum
import pydantic

# Add the project root to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from benny.graph.kg3d.schema import Node, Edge, Proposal, DeltaEvent, NodeCategory, EdgeKind

def py_type_to_ts(py_type):
    if py_type == str:
        return "string"
    if py_type == int or py_type == float:
        return "number"
    if py_type == bool:
        return "boolean"
    if py_type == datetime:
        return "string" # ISO format
    if isinstance(py_type, type) and issubclass(py_type, enum.Enum):
        return " | ".join([f"'{e.value}'" for e in py_type])
    
    origin = get_origin(py_type)
    args = get_args(py_type)
    
    if origin is list or origin is List:
        return f"{py_type_to_ts(args[0])}[]" if args else "any[]"
    if origin is dict or origin is Dict:
        return f"{{ [key: {py_type_to_ts(args[0])}]: {py_type_to_ts(args[1])} }}" if len(args) == 2 else "{ [key: string]: any }"
    if origin is Union:
        # Check if it's Optional (Union[T, None])
        if type(None) in args:
            real_types = [t for t in args if t is not type(None)]
            if real_types:
                return f"{py_type_to_ts(real_types[0])} | null"
            return "any | null"
        return " | ".join([py_type_to_ts(t) for t in args])
    if origin is Literal:
        return " | ".join([f"'{a}'" for a in args])
    
    if isinstance(py_type, type) and issubclass(py_type, pydantic.BaseModel):
        return py_type.__name__
    
    return "any"

def generate_ts():
    models = [NodeCategory, EdgeKind, "NodeMetrics", "PositionHint", Node, Edge, Proposal, DeltaEvent]
    # We need to explicitly handle NodeMetrics and PositionHint since they are nested but not in the root level of schema.py (actually they are in schema.py)
    from benny.graph.kg3d.schema import NodeMetrics, PositionHint
    models = [NodeCategory, EdgeKind, NodeMetrics, PositionHint, Node, Edge, Proposal, DeltaEvent]
    
    output = ["/**", " * KG3D-001 Generated TypeScript Types", " * DO NOT EDIT MANUALLY - generated by scripts/kg3d/emit_ts_types.py", " */", ""]
    
    for model in models:
        if isinstance(model, type) and issubclass(model, enum.Enum):
            output.append(f"export type {model.__name__} = {py_type_to_ts(model)};")
            output.append("")
        elif isinstance(model, type) and issubclass(model, pydantic.BaseModel):
            output.append(f"export interface {model.__name__} {{")
            hints = get_type_hints(model)
            for name, py_type in hints.items():
                ts_type = py_type_to_ts(py_type)
                optional = ""
                # Check for optional in pydantic fields
                field = model.model_fields.get(name)
                if field and not field.is_required():
                    optional = "?"
                output.append(f"  {name}{optional}: {ts_type};")
            output.append("}")
            output.append("")
            
    target_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../frontend/src/types/kg3d.ts"))
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    with open(target_path, "w") as f:
        f.write("\n".join(output))
    print(f"Generated {target_path}")

if __name__ == "__main__":
    generate_ts()
