"""
Studio Executor - Execute visual node graphs from the Studio canvas
Interprets nodes + edges and runs them in topological order
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, Dict, Any, List
from pathlib import Path
from datetime import datetime
import httpx

from ..core.models import LOCAL_PROVIDERS, call_model
from ..governance.lineage import track_workflow_start, track_workflow_complete, track_llm_call, track_tool_execution
from ..core.task_manager import task_manager
import uuid


router = APIRouter()


class StudioNode(BaseModel):
    id: str
    type: str  # trigger, llm, tool, data, logic
    position: Dict[str, float] = {}
    data: Dict[str, Any] = {}


class StudioEdge(BaseModel):
    id: str
    source: str
    target: str


class StudioExecuteRequest(BaseModel):
    nodes: List[StudioNode]
    edges: List[StudioEdge]
    workspace: str = "default"
    message: Optional[str] = None  # User message for trigger nodes


class NodeResult(BaseModel):
    node_id: str
    node_type: str
    status: str  # success, error
    output: Any = None
    error: Optional[str] = None


class StudioExecuteResponse(BaseModel):
    status: str
    node_results: List[NodeResult]
    artifact_path: Optional[str] = None
    final_output: Optional[str] = None


def topological_sort(nodes: List[StudioNode], edges: List[StudioEdge]) -> List[StudioNode]:
    """Sort nodes in execution order based on edges"""
    node_map = {n.id: n for n in nodes}
    in_degree = {n.id: 0 for n in nodes}
    adjacency = {n.id: [] for n in nodes}

    for edge in edges:
        if edge.target in in_degree:
            in_degree[edge.target] += 1
        if edge.source in adjacency:
            adjacency[edge.source].append(edge.target)

    # Kahn's algorithm
    queue = [nid for nid, deg in in_degree.items() if deg == 0]
    sorted_ids = []

    while queue:
        nid = queue.pop(0)
        sorted_ids.append(nid)
        for neighbor in adjacency.get(nid, []):
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0:
                queue.append(neighbor)

    return [node_map[nid] for nid in sorted_ids if nid in node_map]


async def execute_trigger_node(node: StudioNode, message: str, context: Dict) -> Dict:
    """Execute a trigger node — captures the user message"""
    trigger_type = (node.data.get("config") or {}).get("triggerType", "chat")
    return {
        "message": message or "No message provided",
        "trigger_type": trigger_type
    }


async def execute_data_node(node: StudioNode, context: Dict, workspace: str) -> Dict:
    """Execute a data node — RAG search or file write"""
    config = node.data.get("config") or {}
    operation = config.get("operation", "search")

    if operation == "search":
        # RAG search on workspace ChromaDB
        query = context.get("message", "")
        try:
            client = get_chromadb_client(workspace)
            collection = client.get_or_create_collection("knowledge")

            if collection.count() == 0:
                return {"results": [], "message": "Knowledge base empty — please ingest documents first"}

            results = collection.query(
                query_texts=[query],
                n_results=min(5, collection.count())
            )

            formatted = []
            context_text = ""
            for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
                source = meta.get("source", "Unknown")
                formatted.append({"text": doc, "source": source})
                context_text += f"[Source: {source}]\n{doc}\n\n"

            return {
                "results": formatted,
                "context_text": context_text,
                "count": len(formatted)
            }
        except Exception as e:
            return {"error": str(e), "results": []}

    elif operation == "write":
        # Write the LLM output to a .md file
        content = context.get("llm_output", "No content generated")
        filename = config.get("path", "output.md")
        if not filename.endswith(".md"):
            filename += ".md"

        try:
            out_path = get_workspace_path(workspace, "data_out") / filename
            out_path.parent.mkdir(parents=True, exist_ok=True)

            # Build a proper markdown document
            md_content = f"# {filename.replace('.md', '').replace('_', ' ').title()}\n\n"
            md_content += f"*Generated by Benny Studio — {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n\n"
            md_content += "---\n\n"
            md_content += content

            out_path.write_text(md_content, encoding="utf-8")

            return {
                "written": True,
                "path": str(out_path),
                "filename": filename,
                "download_url": f"http://localhost:8005/api/files/{workspace}/data_out/{filename}"
            }
        except Exception as e:
            return {"error": str(e), "written": False}

    elif operation == "read":
        filename = config.get("path", "")
        try:
            path = get_workspace_path(workspace, "data_in") / filename
            if not path.exists():
                path = get_workspace_path(workspace, "data_out") / filename
            if path.exists():
                content = path.read_text(encoding="utf-8")
                return {"content": content, "filename": filename}
            return {"error": f"File not found: {filename}"}
        except Exception as e:
            return {"error": str(e)}

    return {"error": f"Unknown data operation: {operation}"}


async def execute_llm_node(node: StudioNode, context: Dict, workspace: str, run_id: Optional[str] = None) -> Dict:
    """
    Execute an LLM Agent node with tool-calling capabilities.
    The agent receives attached skills and autonomously decides to call them.
    """
    from ..core.skill_registry import registry
    import json

    config = node.data.get("config") or {}
    model_name = config.get("model", "Qwen3-8B-Hybrid")
    system_prompt = config.get("systemPrompt", "You are a helpful AI assistant.")
    attached_skills = config.get("skills", [])  # List of skill IDs

    # Get tool schemas for the attached skills
    tools = None
    if attached_skills:
        tool_schemas = registry.get_tool_schemas(attached_skills, workspace)
        if tool_schemas:
            tools = tool_schemas

    # Build initial messages array
    messages = [
        {"role": "system", "content": system_prompt}
    ]

    user_message = context.get("message", "")
    rag_context = context.get("context_text", "")
    
    if rag_context:
        messages.append({
            "role": "user", 
            "content": f"CONTEXT FROM PREVIOUS NODES:\n{rag_context}\n\nUSER QUESTION:\n{user_message}"
        })
    else:
        messages.append({"role": "user", "content": user_message})

    # Determine provider config (using Lemonade as primary local provider)
    provider_config = LOCAL_PROVIDERS.get("lemonade", LOCAL_PROVIDERS.get("ollama"))
    if not provider_config:
        return {"error": "No local provider configured"}
        
    api_base = provider_config["base_url"]
    chat_url = f"{api_base}/chat/completions"
    
    # Tool-calling loop (max 5 iterations to prevent infinite loops)
    max_steps = 5
    current_step = 0
    total_tokens = 0
    executed_tools = []

    async with httpx.AsyncClient(timeout=300.0) as client:
        while current_step < max_steps:
            current_step += 1
            
            payload = {
                "model": model_name,
                "messages": messages,
                "temperature": config.get("temperature", 0.7)
            }
            if tools:
                payload["tools"] = tools

            try:
                response = await client.post(
                    chat_url,
                    json=payload,
                    headers={"Content-Type": "application/json"}
                )
            except Exception as e:
                return {"error": f"LLM connection error: {str(e)}", "response": None}

            if response.status_code != 200:
                # FastFlowLM models might not support tools properly.
                # If tool-calling fails, try a fallback without tools.
                if tools and ("tool" in response.text.lower() or "function" in response.text.lower()):
                    payload.pop("tools")
                    response = await client.post(chat_url, json=payload, headers={"Content-Type": "application/json"})
                    if response.status_code != 200:
                        return {"error": f"LLM error: {response.status_code} {response.text}", "response": None}
                else:
                    return {"error": f"LLM error: {response.status_code} {response.text}", "response": None}

            data = response.json()
            message = data["choices"][0]["message"]
            usage = data.get("usage", {})
            total_tokens += usage.get("total_tokens", 0)

            # Record LLM call to Governance Log
            if run_id:
                track_llm_call(
                    parent_run_id=run_id,
                    model=model_name,
                    provider="lemonade", 
                    usage=usage,
                    parent_job_name="studio_workflow"
                )

            # Record assistant message
            messages.append(message)

            # Check if LLM wants to call tools
            if "tool_calls" in message and message["tool_calls"]:
                tool_calls = message["tool_calls"]
                
                # Execute each tool call
                for tc in tool_calls:
                    func_name = tc["function"]["name"]
                    call_id = tc["id"]
                    try:
                        args = json.loads(tc["function"]["arguments"])
                    except json.JSONDecodeError:
                        args = {}

                    # Run the skill via registry
                    result_str = registry.execute_skill(func_name, workspace, **args)
                    executed_tools.append({"name": func_name, "args": args})

                    # Track tool execution in audit log
                    if run_id:
                        track_tool_execution(
                            parent_run_id=run_id,
                            tool_name=func_name,
                            tool_args=args, # Refactored to tool_args
                            success=True,
                            parent_job_name="studio_workflow"
                        )

                    # Add tool response to messages
                    messages.append({
                        "role": "tool",
                        "tool_call_id": call_id,
                        "name": func_name,
                        "content": result_str
                    })
                
                # Loop continues to send tool results to LLM
                continue

            # If no tool calls, this is the final answer
            answer = message.get("content", "")
            return {
                "response": answer,
                "model": model_name,
                "tokens": total_tokens,
                "tool_executions": executed_tools
            }

        # If loop maxes out
        return {
            "error": "Agent execution max steps reached",
            "response": messages[-1].get("content", ""),
            "tool_executions": executed_tools
        }


@router.post("/workflows/execute", response_model=StudioExecuteResponse)
async def execute_studio_workflow(request: StudioExecuteRequest):
    """Execute a Studio node graph end-to-end"""
    if not request.nodes:
        raise HTTPException(400, "No nodes in workflow")

    # Sort nodes in execution order
    sorted_nodes = topological_sort(request.nodes, request.edges)

    run_id = f"studio_{str(uuid.uuid4())[:12]}"
    task_manager.create_task(request.workspace, "studio_workflow", task_id=run_id)
    track_workflow_start(
        run_id, 
        "studio_workflow", 
        request.workspace,
        inputs=[f"node_{n.id}" for n in request.nodes],
        outputs=[f"studio_run_{run_id}"]
    )

    # Execution context — accumulates outputs between nodes
    context: Dict[str, Any] = {
        "message": request.message or "",
        "workspace": request.workspace
    }

    node_results: List[NodeResult] = []
    artifact_path = None
    final_output = None

    for node in sorted_nodes:
        try:
            if node.type == "trigger":
                output = await execute_trigger_node(node, request.message or "", context)
                context["message"] = output.get("message", context["message"])

            elif node.type == "data":
                output = await execute_data_node(node, context, request.workspace)
                # Propagate RAG context forward
                if "context_text" in output:
                    context["context_text"] = output["context_text"]
                # Track file write artifacts
                if output.get("written"):
                    artifact_path = output.get("path")

            elif node.type == "llm":
                output = await execute_llm_node(node, context, request.workspace, run_id=run_id)
                # Propagate LLM output forward for downstream nodes
                if output.get("response"):
                    context["llm_output"] = output["response"]
                    final_output = output["response"]

            elif node.type == "tool":
                output = {"message": "Tool node executed (stub)"}

            elif node.type == "logic":
                output = {"message": "Logic node passed"}

            else:
                output = {"message": f"Unknown node type: {node.type}"}

            has_error = "error" in output and output["error"]
            node_results.append(NodeResult(
                node_id=node.id,
                node_type=node.type,
                status="error" if has_error else "success",
                output=output,
                error=output.get("error") if has_error else None
            ))

        except Exception as e:
            node_results.append(NodeResult(
                node_id=node.id,
                node_type=node.type,
                status="error",
                error=str(e)
            ))

    overall_status = "completed" if all(r.status == "success" for r in node_results) else "failed"

    # Finalize Audit
    task_manager.update_task(run_id, status=overall_status, progress=100)
    track_workflow_complete(run_id, "studio_workflow", [r.node_type for r in node_results], 0)

    return StudioExecuteResponse(
        status=overall_status,
        node_results=node_results,
        artifact_path=artifact_path,
        final_output=final_output
    )
