"""AOS-001 Phase 6 — BDD compiler: Gherkin feature text → pytest stub module.

Public API
----------
  compile_to_pytest(feature_text: str) -> str
      Parses Gherkin feature text and emits a deterministic pytest stub file.

      Determinism guarantee (AOS-F21 / R7 mitigation):
      - Scenarios are sorted by their slugified title before emission.
      - The slug transform is byte-stable across Python minor versions
        (uses only ``str.lower()`` + ``re.sub`` — no dict iteration).
      - Re-running the compiler on the same input always produces
        byte-identical output.

AOS requirements covered
------------------------
  F21   compile_to_pytest() produces sorted, deterministic pytest stubs.
  R7    MITIGATED: sorted iteration + stable slug avoids Python minor-version
        dict-order variability. ``test_aos_f21_compile_to_pytest_deterministic``
        verifies byte-equality across two consecutive calls.

Placement note
--------------
Module lives in benny/sdlc/ (not benny/graph/) — no langgraph dependency.

Dependencies: stdlib only (re, textwrap).
No new top-level dependency is introduced.
"""

from __future__ import annotations

import re
import textwrap


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _slugify(text: str) -> str:
    """Convert *text* to a valid Python identifier suitable for test naming.

    Transform rules (stable across Python versions):
    1. Lower-case everything.
    2. Replace any run of non-alphanumeric characters with a single ``_``.
    3. Strip leading/trailing underscores.
    4. Fall back to ``"unnamed"`` if the result is empty.

    Parameters
    ----------
    text:
        Scenario title or any other human-readable string.

    Returns
    -------
    str
        A lower-case, underscore-separated Python-safe identifier.
    """
    slug = text.lower()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    slug = slug.strip("_")
    return slug or "unnamed"


def _parse_scenarios(feature_text: str) -> list[dict]:
    """Parse Gherkin text and return a list of scenario dicts.

    Each dict has keys: ``title``, ``given``, ``when``, ``then``.
    Only the **first** Given / When / Then line per scenario block is
    captured; continuation lines (``And``, ``But``) and ``Background``
    sections are ignored for this minimal parser.

    Parameters
    ----------
    feature_text:
        Raw Gherkin feature file content.

    Returns
    -------
    list[dict]
        Ordered list of parsed scenarios (order matches the file).
    """
    scenarios: list[dict] = []
    current: dict | None = None

    for raw_line in feature_text.splitlines():
        line = raw_line.strip()
        lower = line.lower()

        if lower.startswith("scenario:"):
            if current is not None:
                scenarios.append(current)
            title = line[len("scenario:"):].strip()
            current = {"title": title, "given": "", "when": "", "then": ""}

        elif current is not None:
            if lower.startswith("given ") and not current["given"]:
                current["given"] = line[len("given "):].strip()
            elif lower.startswith("when ") and not current["when"]:
                current["when"] = line[len("when "):].strip()
            elif lower.startswith("then ") and not current["then"]:
                current["then"] = line[len("then "):].strip()

    if current is not None:
        scenarios.append(current)

    return scenarios


# ---------------------------------------------------------------------------
# Output templates
# ---------------------------------------------------------------------------

_HEADER = """\
# Auto-generated by benny.sdlc.bdd.compile_to_pytest — DO NOT EDIT
# Regenerate with: benny bdd compile <feature_file>
import pytest
"""

_STUB_TEMPLATE = """\
def test_{slug}():
    \"\"\"
    Given: {given}
    When:  {when}
    Then:  {then}
    \"\"\"
    pytest.fail("BDD stub — not yet implemented: {title!r}")
"""


# ---------------------------------------------------------------------------
# Public API (AOS-F21)
# ---------------------------------------------------------------------------


def compile_to_pytest(feature_text: str) -> str:
    """Compile Gherkin feature text to a deterministic pytest stub module.

    Scenarios are sorted by their slugified title before emission so that
    the output is byte-identical across repeated invocations regardless of
    the order in which scenarios appear in the source (AOS-F21 / R7
    mitigation: sorted iteration, stable hash).

    Parameters
    ----------
    feature_text:
        Gherkin feature file content (as a string).  Mixed line endings are
        normalised by ``str.splitlines()``.

    Returns
    -------
    str
        A complete Python test module (``import pytest`` + one ``test_``
        function per scenario, each calling ``pytest.fail``).  The output
        is valid Python 3 and byte-identical for the same *feature_text*.

    Examples
    --------
    >>> src = \"\"\"
    ... Feature: Login
    ...
    ...   Scenario: Happy path
    ...     Given a valid username and password
    ...     When the user submits the login form
    ...     Then they are redirected to the dashboard
    ... \"\"\"
    >>> code = compile_to_pytest(src)
    >>> "def test_happy_path" in code
    True
    >>> code.count("pytest.fail") == 1
    True
    """
    scenarios = _parse_scenarios(feature_text)

    # Sort by slug for determinism — R7 mitigation
    scenarios.sort(key=lambda s: _slugify(s["title"]))

    parts: list[str] = [_HEADER]

    for scenario in scenarios:
        slug = _slugify(scenario["title"])
        stub = _STUB_TEMPLATE.format(
            slug=slug,
            given=scenario["given"] or "(not specified)",
            when=scenario["when"] or "(not specified)",
            then=scenario["then"] or "(not specified)",
            title=scenario["title"],
        )
        parts.append(stub)

    return "\n".join(parts)
