"""AAMP-001 Phase 1 — Deterministic skin-pack scaffold generator (AAMP-F33).

Public API
----------
  scaffold_skin(skin_id, *, drafts_dir) -> Path
      Create a deterministic draft directory tree for a new skin at
      ``drafts_dir/<skin_id>/``.  Returns the root path.

      The emitted ``skin.manifest.json`` always has ``"signature": null``
      (AAMP-F33, GATE-AAMP-AUTOSIGN-1).  The directory is idempotent:
      calling scaffold_skin twice with the same arguments produces the
      same files (AAMP-F33 deterministic contract).

      Raises
      ------
      ValueError   ``skin_id`` contains path-separator characters or is empty.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

from .contracts import SkinManifest, SkinTokens, SkinCliPalette

# skin_id must be a safe directory name: alphanumerics, hyphens, underscores only
_SAFE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_\-]{0,63}$")

# Sub-directories created inside the draft
_SUBDIRS = ("sprites", "shaders", "sounds")

# Minimal placeholder shader so the shader sub-dir is non-empty
_PLACEHOLDER_SHADER = """\
// post-process glow — replace with your GLSL (GLSL ES 3.00)
precision mediump float;
uniform sampler2D uScene;
in vec2 vUv;
out vec4 fragColor;

void main() {
    fragColor = texture(uScene, vUv);
}
"""

# Minimal README inside the draft
_DRAFT_README = """\
# {skin_id} — AgentAmp skin draft

This directory was generated by `benny agentamp scaffold-skin {skin_id}`.

## Next steps

1. Edit `skin.manifest.json` — customise tokens, sprites, shaders, sounds.
2. Add assets under `sprites/`, `shaders/`, `sounds/`.
3. Pack:    `benny agentamp pack . --out {skin_id}.aamp`
4. Sign:    `benny agentamp sign {skin_id}.aamp`
5. Install: `benny agentamp install {skin_id}.aamp`

The manifest's `"signature"` field is intentionally `null` in this draft.
Do NOT set `aamp.designer.auto_sign = true` — that flag must remain false
(GATE-AAMP-AUTOSIGN-1).
"""


def scaffold_skin(
    skin_id: str,
    *,
    drafts_dir: os.PathLike | str | None = None,
) -> Path:
    """Create a deterministic draft skin directory at ``drafts_dir/<skin_id>/``.

    Parameters
    ----------
    skin_id:
        Identifier for the skin.  Must match ``[A-Za-z0-9][A-Za-z0-9_-]{0,63}``.
    drafts_dir:
        Parent directory for the draft.  Defaults to
        ``${BENNY_HOME}/agentamp/drafts`` (or ``./agentamp/drafts`` if
        BENNY_HOME is not set).

    Returns
    -------
    Path
        Absolute path to the created draft directory.
    """
    if not _SAFE_ID_RE.match(skin_id or ""):
        raise ValueError(
            f"skin_id {skin_id!r} is invalid — "
            "must match [A-Za-z0-9][A-Za-z0-9_-]{{0,63}}"
        )

    if drafts_dir is None:
        benny_home = os.environ.get("BENNY_HOME", ".")
        drafts_dir = Path(benny_home) / "agentamp" / "drafts"

    root = Path(drafts_dir) / skin_id
    root.mkdir(parents=True, exist_ok=True)

    # Sub-directories
    for sub in _SUBDIRS:
        (root / sub).mkdir(exist_ok=True)

    # Placeholder shader (deterministic content)
    shader_path = root / "shaders" / "post_glow.frag.glsl"
    if not shader_path.exists():
        shader_path.write_text(_PLACEHOLDER_SHADER, encoding="utf-8")

    # skin.manifest.json — signature MUST be null (AAMP-F33, GATE-AAMP-AUTOSIGN-1)
    manifest = SkinManifest(id=skin_id)
    manifest_path = root / "skin.manifest.json"
    # Always write (idempotent: content is fully determined by skin_id + defaults)
    manifest_dict = manifest.model_dump(mode="json")
    assert manifest_dict["signature"] is None, "scaffold must emit null signature"
    manifest_path.write_text(
        json.dumps(manifest_dict, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    # README
    readme_path = root / "README.md"
    if not readme_path.exists():
        readme_path.write_text(
            _DRAFT_README.format(skin_id=skin_id),
            encoding="utf-8",
        )

    return root.resolve()
